# Generated by Django 3.1a1 on 2020-11-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_auto_20200805_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
